name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        brew install docker
        colima start
        docker build . --file Dockerfile --tag workflow
        docker save -o workflow.tar workflow
    - uses: actions/upload-artifact@v4
      with: 
        path: ./workflow.tar
